SELECT DATE_FORMAT(NOW(), '%y');
SELECT DATE_FORMAT(NOW(), '%Y');

SELECT DATE_FORMAT(NOW(), '%m %Y');
SELECT DATE_FORMAT(NOW(), '%M %Y');

SELECT DATE_FORMAT(NOW(), '%d %M %Y');
SELECT DATE_FORMAT(NOW(), '%D %M %Y');

SELECT TIME_FORMAT(NOW(), '%h:%i:%s %p');
